language: java
sudo: false
install: true


jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean package

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
